arana-db/arana

pkg/mysql/server.go
=> fix:when client deprecate eof packet, should write ok packet instead

pkg/mysql/server.go
客户端发送请求后，并没有发送com_quit包，就直接发FIN要关闭连接了
这时候，arana依然处于一个readPacket的状态，先解析接收到包的header，但是读取到EOF，返回了错误，这里直接panic掉了(此时arana，并不知道客户端是不是出了问题)。当arana在处理server端协议的时候，遇到EOF，打日志，不报panic
Fixes #58 
```release-note
```
=> fix: client exit ,but do not send com_quit

pkg/runtime/plan/simple_select.go
For #92 .
```release-note
```
Now, it is support those scenes:
```
select * from student order by uid asc, name desc;
select * from student t order by t.uid asc, name desc;
select uid as a from student t order by a asc;
```
=> Support single db, multi-table order by SQL

pkg/executor/redirect.go, pkg/runtime/ast/alter_table.go, pkg/runtime/ast/ast.go, pkg/runtime/ast/ast_test.go, pkg/runtime/ast/model.go, pkg/runtime/ast/proto.go, pkg/runtime/optimize/optimizer.go, pkg/runtime/optimize/optimizer_test.go, pkg/runtime/plan/alter_table.go, pkg/runtime/plan/transparent.go, test/integration_test.go
Fixes #165 
```release-note
```
=> feat: alter table statement 

pkg/runtime/ast/ast.go, pkg/runtime/ast/ast_test.go, pkg/runtime/ast/insert.go, pkg/runtime/optimize/optimizer.go, pkg/runtime/optimize/optimizer_test.go, pkg/runtime/plan/insert_select.go
Fixes #187 
Only support insert-select statement for non-sharding table.
1) INSERT INTO `student` SELECT * FROM `student_tmp`
2) INSERT INTO `student`(`id`, `name`) SELECT `emp_no`,`name` FROM `employees` LIMIT 10,2
3) INSERT INTO `student`(`id`, `name`) SELECT `emp_no`,`name` FROM `employees` ON DUPLICATE KEY UPDATE `version` = `version`+1, `modified_at` = NOW()
4) INSERT INTO `student` SELECT `id`,`score` FROM `student_tmp` UNION SELECT `id`*10,`score`*10 FROM `student_tmp`
```release-note
```
=> support insert select stmt for non-sharding table

conf/config.yaml, go.mod, pkg/boot/boot.go, pkg/boot/discovery.go, pkg/config/file/file.go, pkg/config/model.go, pkg/constants/const.go, pkg/mysql/client.go, pkg/mysql/conn.go, pkg/runtime/runtime.go
Fixes #292 #281 
```release-note
```
=> optimize maxAllowedPacket config fix: #292 #281

integration_test/scene/db_tbl_rw/integration_test.go, pkg/runtime/ast/ast.go, pkg/runtime/ast/ast_test.go, pkg/runtime/ast/misc.go, pkg/runtime/ast/show.go
improve convert of `show table status ...` in ast, 'from` and `in` is same.
Fixes #361 
```release-note
```
=> improve: show_table_status ast node

pkg/sequence/snowflake/snowflake.go
The format of the snowflake id is 
0 + timestamp(41 bit) + work id(10 bit) + sequence id(12 bit)
and the timestamp should be offset 22 bits to the left.
Fixes #
```release-note
```
=> fix snowflake id offset

pkg/admin/router/db_groups.go, pkg/boot/discovery.go, pkg/boot/proto.go
add missing interfaces && add group api 
ref #344
=> feat: add group api for UI module #344

conf/config.yaml, integration_test/config/shadow/config.yaml, integration_test/scene/shadow/integration_test.go, integration_test/testcase/casetest.yaml, pkg/constants/const.go, pkg/proto/rule/shadow.go, pkg/runtime/ast/expression_atom.go, pkg/runtime/optimize/dml/delete.go, pkg/runtime/optimize/dml/insert.go, pkg/runtime/optimize/dml/select.go, pkg/runtime/optimize/dml/update.go, pkg/runtime/optimize/sharder.go, pkg/runtime/plan/dal/show_tables.go, pkg/runtime/rule/evaluator.go, scripts/init.sql, scripts/sharding.sql, test/dataset.go
1. create shadow tables in init.sql & sharding.sql
2. hide shadow tables for "show tables" command
3. impl shadow match hint rule (only select)
4. support shadow type match regex (only select)
Test Cases:
SELECT name FROM student WHERE uid = 1; //sharding
SELECT name FROM student WHERE name = 'lilei'; //fullscan
SELECT name FROM student WHERE uid = 1 and name = 'lilei'; //sharding
SELECT name FROM student WHERE uid = 1 or name = 'lilei'; //fullscan
/*A! shadow(shadow) */ SELECT name FROM student WHERE uid = 1; //sharding shadow tables
/*A! shadow(shadow) */ SELECT name FROM student WHERE name = 'lilei'; //fullscan shadow tables
/*A! shadow(shadow) */ SELECT name FROM student WHERE uid = 1 and name = 'lilei'; //sharding shadow tables
/*A! shadow(shadow) */ SELECT name FROM student WHERE …
=> Feature: support shadow type match regex (#365)

pkg/sequence/group/group.go, pkg/sequence/group/group_test.go
add  group sequence implementation.
ref #94 
```release-note
```
=> feat(sequence): add group sequence implementation

pkg/boot/discovery.go, pkg/config/config_writer.go
=> feat(config): add tenant&cluster config support

pkg/runtime/function2/cast.go, pkg/runtime/function2/cast_test.go
Signed-off-by: Wyatt Jia <i@eventloop.live>
Add `CAST` function placeholder logic for whole `CAST` entrypoints.
ref #465 
```release-note
```
=> feat: add CAST function placeholder.

pkg/runtime/function2/length.go, pkg/runtime/function2/length_test.go
Fixes #502 
```release-note
```
=> feat:length

pkg/runtime/function2/concat.go, pkg/runtime/function2/concat_test.go
Signed-off-by: charlie <charlie1213800@gmail.com>
According to the doc of MYSQL, when args of CONCAT have any NULL, it should also return NULL
before
```
mysql> select concat(1, 2, NULL, max(id)) from student;
+-----------------------------+
| concat(1, 2, NULL, max(id)) |
+-----------------------------+
| 12NULL1                     |
+-----------------------------+
1 row in set (0.03 sec)
```
now
```
mysql> select concat(1, 2, NULL, max(id)) from student;
+-----------------------------+
| concat(1, 2, NULL, max(id)) |
+-----------------------------+
| NULL                        |
+-----------------------------+
1 row in set (0.03 sec)
```
Fixes #
**Does this PR introduce a user-facing …
=> fix: when args of CONCAT have any NULL, it should return NULL

pkg/runtime/function2/upper.go, pkg/runtime/function2/upper_test.go
Fixes #513 
```release-note
```
=> feat: support Mysql Upper Function

pkg/runtime/function/right.go, pkg/runtime/function/right_test.go
Fixes #519 
```release-note
```
=> feat: add mysql right function

Dockerfile, pkg/executor/redirect.go, pkg/mysql/server.go
Handle empty query correctly, will follow the normal MySQL behavior below:
Fixes #641 
```release-note
```
=> fix: handle empty query correctly

justfile, pkg/mysql/client.go, pkg/mysql/conn.go, pkg/mysql/execute_handle.go, pkg/mysql/server.go, pkg/runtime/runtime.go, pkg/util/misc/misc.go
Fixes #639 
```release-note
```
=> fix: connection leak when concurrent updates

go.mod, go.sum, pkg/runtime/ast/ast.go, pkg/runtime/ast/insert.go, pkg/runtime/ast/model.go, pkg/runtime/ast/select.go, pkg/runtime/optimize/dml/insert.go, test/integration_test.go
**What this PR does**:  deliver mysql optimizer hints from parser to mysql service
**Which issue(s) this PR fixes**: https://github.com/arana-db/arana/issues/647
Fixes #
**Special notes for your reviewer**:  This PR depend on arana/parser.Restore function to handle hints in arana, consider arana will import other ast packages, what is the more graceful usage?
**Does this PR introduce a user-facing change?**: NONE
```release-note
```
=> Dev hint transform

pkg/constants/mysql/constants.go, pkg/runtime/optimize/dml/select.go
Fixes #660 
```release-note
```
=> fix:select from table not exist cause panic

cmd/admin/admin.go, conf/bootstrap.yaml, pkg/executor/redirect.go, pkg/trace/jaeger/jaeger.go, pkg/trace/trace.go, pkg/util/log/logging.go
1. add composite logger to manage main/sql/tx logger
2. support to parse and propagate the trace context to logging
3. make the logger achieve context level isolation
Fixes #596 
```release-note
```
=> feat(log) : support logging with context(#596)

pkg/dataset/filter_test.go, pkg/dataset/reduce_test.go, pkg/dataset/transform_test.go
=> add unit test for function (#708)

pkg/resultx/resultx_test.go
Fixes #728 
```release-note
NONE
```
=> test: resultx ut

pkg/reduce/reduce_test.go, pkg/util/env/env_test.go, pkg/util/file/file_test.go, pkg/util/identity/identity_test.go, pkg/util/match/slice_match_test.go, pkg/util/runes/rune_test.go
=> Add unit test

pkg/boot/discovery.go, pkg/runtime/ast/ast_test.go, pkg/runtime/optimize/dal/show_tables.go, pkg/runtime/plan/dal/show_tables.go
Fixes #677 
```release-note
NONE
```
=> fix: show tables from database

pkg/reduce/reduce_test.go, pkg/runtime/namespace/namespace.go, pkg/runtime/namespace/namespace_test.go
=> add unit test for function (#746)

go.mod, pkg/boot/discovery_test.go, pkg/boot/discovery_watch.go
=> fix: send to closed chan in discovery

CHANGELOG.md
=> chore(release): prepare for 0.2.0

pkg/config/etcd/etcd.go, pkg/config/etcd/etcd_test.go
Fixes #790 
```release-note
NONE
```
=> test: etcd ut

conf/bootstrap.docker.yaml
docker-compose admin platform panic
Fixes #805 / #807
=> fix: docker-compose admin platform panic (#805) (#807)

conf/bootstrap.yaml, pkg/admin/config.go, pkg/admin/config_service.go, pkg/admin/router/clusters.go, pkg/config/misc.go, pkg/config/model.go, pkg/runtime/optimize/ddl/create_table.go, scripts/sharding.sql
=> Support dts to replica databases/groups

pkg/config/misc.go, pkg/config/misc_test.go
Fixes #784 
```release-note
NONE
```
=> test: misc ut
