- .gitmodules
- pkg/config/config.go
- pkg/config/db.go
> 修复解析配置role、type字段 fix #3

- .github/workflows/reviewdog.yml
- .gitmodules
- pkg/mysql/server.go
- test/integration_test.go
> fix: ComQuery write row not correct

- cmd/cmd.go
- docker/conf/config.yaml
- makefile
- pkg/config/config.go
- pkg/executor/redirect.go
- pkg/filters/filters.go
- pkg/mysql/server.go
- pkg/proto/interface.go
complete filter mechanism. with this pr, developer can expand some filter functions.
> complete filter mechanism

- .github/workflows/github-actions.yml
Fixes #
```release-note
NONE
```
> feat:action mysql

- .github/workflows/github-actions.yml
Fixes #
```release-note
NONE
```
> action Upgrade Go version to 1.16

- test/integration_test.go
use native go sql driver instead of orm framework
> use native go sql driver instead of orm framework

- test/integration_test.go
Fixes #
```release-note
NONE
```
> style：optimizing test cases, add conn close

- docs/README_ZH.md
> add README

- .github/workflows/github-actions.yml
- docker/docker-compose.yaml
- makefile
Fixes #
https://github.com/dubbogo/arana/issues/19
```release-note
NONE
```
> feat：action ci test

- pkg/config/db.go
- pkg/executor/redirect.go
- pkg/mysql/client.go
Fixes #31 
```release-note
```
> remove max rows

- docker/docker-compose.yaml
change from 8888 to 3306 for debug on local
Fixes #
```release-note
```
> Imp: change host mysql port

- .golangci.yml
- cmd/cmd.go
- pkg/executor/redirect.go
- pkg/mysql/client.go
- pkg/mysql/server.go
- pkg/mysql/statement.go
- pkg/proto/interface.go
- test/integration_test.go
- third_party/pools/resource_pool.go
- third_party/pools/resource_pool_flaky_test.go
> ftr: support binary protocol from arana to physics db

- test/integration_test.go
```
simplify integration test conf
```
> simplify integration test conf

- pkg/proto/rule/database_table.go
- pkg/runtime/function/function_test.go
fix typo
Fixes #
```release-note
```
> chore: fix typo

- pkg/mysql/server.go
- pkg/proto/runtime.go
- pkg/runtime/function/function.go
- pkg/runtime/misc/other.go
- pkg/runtime/optimize/optimizer.go
- pkg/runtime/optimize/optimizer_test.go
- pkg/runtime/optimize/sharder.go
- pkg/runtime/plan/simple.go
- pkg/runtime/plan/sql_utils.go
- pkg/runtime/plan/union.go
- pkg/runtime/xxast/ast_crud.go
- pkg/runtime/xxast/ast_describe.go
- pkg/runtime/xxast/ast_expression.go
- pkg/runtime/xxast/ast_expression_atom.go
- pkg/runtime/xxast/ast_function.go
- pkg/runtime/xxast/ast_predicate.go
- pkg/runtime/xxast/ast_select_element.go
- pkg/runtime/xxast/ast_show.go
- pkg/runtime/xxast/ast_union.go
- pkg/runtime/xxast/types.go
- pkg/runtime/xxast/xxast.go
- test/integration_test.go
**What this PR does**:  
optimizer skeleton, which can be used to generate a simple query plan, pls view this UT: `pkg/runtime/optimize/optimizer_test.go`
Fixes #
```release-note
```
> feat: add simple optimizer skeleton

- pkg/mysql/client_test.go
> add test 4 pares handshake

- pkg/mysql/client.go
- pkg/mysql/client_test.go
- pkg/mysql/conn_test.go
- pkg/mysql/encoding_test.go
> test case 4 client

- pkg/runtime/xxast/xxast.go
> [WIP] insert/update/delete clause support

- docker/conf/config.yaml
- pkg/config/config.go
- pkg/executor/redirect.go
- pkg/selector/db_manager.go
- pkg/selector/weight_random.go
- pkg/selector/weight_random_test.go
add read write split. https://dubbo-kylin.yuque.com/staff-rvuh2g/qau55u/nshtei
Fixes #
```release-note
```
> feat: add write read split

- pkg/config/config.go
- pkg/config/db.go
- pkg/config/db_test.go
- pkg/config/testdata/config.yaml
Fixes #
add new config struct
```release-note
```
> add new config struct

- pkg/config/config_test.go
> add unit test for config.go .

- pkg/config/config.go
- pkg/executor/redirect.go
用 default 替换指针类型
Fixes #
```release-note
```
> fix: point to int

- pkg/executor/redirect_test.go
> add unit test for redirect.go

- pkg/runtime/xxast/ast_function.go
**What this PR does**: bug fix, restore function args correctly
Fixes #
```release-note
```
> fix: restore function args correctly

- pkg/executor/redirect_test.go
- pkg/filters/filters_test.go
> add new unit test.

- pkg/config/db.go
- pkg/executor/redirect.go
adapter V2 config for master slave split.
Fixes #
```release-note
```
> Opt: adapter V2 config for master slave split

- pkg/mysql/fields_test.go
- pkg/mysql/result_test.go
- pkg/mysql/rows_test.go
> add unit test for fields.go, result.go, rows.go.

- pkg/config/config_test.go
- pkg/constants/mysql/type_test.go
- pkg/executor/redirect_test.go
- pkg/filters/filters_test.go
> Optimize unit test code.

- README.md
- README_CN.md
- README_ZH.md
> Ftr: add codecov in readme

- pkg/proto/interface_test.go
- pkg/proto/rule/topology_test.go
- pkg/resource/data_source_test.go
> add unit test.

- pkg/mysql/conn.go
- pkg/mysql/server.go
fix incorrect db name from USE_DATABASE statement.
Fixes #97 
```release-note
```
> fix: parse dbname from USE_DATABASE correctly

- .github/workflows/github-actions.yml
- .github/workflows/licence-checker.yml
- .github/workflows/release.yml
- .gitmodules
1. remove unless git submodules
2. use dingtalk webhook instead of actions
3. actions workflow refinement
Fixes #
```release-note
```
> ci: adjust some actions

- go.mod
- go.sum
- pkg/config/config.go
default not work when parse config
Fixes #112 
```release-note
```
> fix: default not work when parse config

- pkg/config/config.go
- pkg/executor/redirect.go
- pkg/runtime/ast/ast.go
- pkg/runtime/ast/model.go
- pkg/runtime/optimize/optimizer.go
- pkg/runtime/plan/simple_delete.go
- pkg/runtime/plan/transparent.go
- test/integration_test.go
Implement `DELETE` statement.
Fixes #110 
```release-note
```
> feat: implement delete from sharding table

- pkg/merge/aggregator.go
- pkg/merge/aggregator/add_aggregator.go
- pkg/merge/aggregator/add_aggregator_test.go
- pkg/merge/aggregator/avg_aggregator.go
- pkg/merge/aggregator/avg_aggregator_test.go
- pkg/merge/aggregator/max_aggregator.go
- pkg/merge/aggregator/max_aggregator_test.go
- pkg/merge/aggregator/min_aggregator.go
- pkg/merge/aggregator/min_aggregator_test.go
- pkg/merge/impl/group_by/group_by_stream_merge_rows.go
> chore: fix code spelling mistake.

- .golangci.yml
- .pre-commit-config.yaml
- docker/Dockerfile
- docker/conf/bootstrap.yaml
- docker/conf/config.yaml
- docker/docker-compose.yaml
- docker/scripts/init.sql
- docker/scripts/sequence.sql
- docker/scripts/sharding.sql
- pkg/boot/options.go
- pkg/boot/plugin.go
- pkg/config/api.go
- pkg/config/config.go
- pkg/config/etcd/etcd.go
- pkg/config/etcd/etcd_test.go
- pkg/config/file/file.go
- pkg/config/model.go
- test/testcontainer_mysql_test.go
- testdata/fake_bootstrap.yaml
> add license heder & fixes unit test variable name.

- pkg/boot/discovery.go
- pkg/runtime/runtime.go
> rename variable to make semantic clearer

- pkg/executor/redirect.go
- pkg/runtime/ast/ast.go
- pkg/runtime/ast/proto.go
- pkg/runtime/ast/truncate.go
- pkg/runtime/optimize/optimizer.go
- pkg/runtime/plan/transparent.go
- pkg/runtime/plan/truncate.go
Fixes #114 .
```release-note
```
> Support truncate table xxx.

- docker/conf/bootstrap.yaml
- go.mod
- go.sum
- pkg/mysql/conn.go
> add net conn check. 

- .github/workflows/docker-image.yml
Add workflow to auto-build docker image.
Fixes #
```release-note
```
> chore(ci): add auto-build docker image

- .github/workflows/docker-image.yml
> fix: wrong branch name in docker-image workflow

- pkg/mysql/fields.go
- pkg/runtime/plan/show_databases.go
- test/integration_test.go
Fixes #149 
```release-note
NONE
```
> fix:show databases set the column type to varchar

- pkg/proto/rule/rule.go
- pkg/runtime/optimize/optimizer.go
- pkg/runtime/plan/show_tables.go
show tables
Fixes #77
```release-note
```
> feat: add show tables

- pkg/mysql/rows.go
> Ftr: add binary & text encode

- pkg/mysql/client.go
- pkg/mysql/conn.go
- pkg/runtime/conn_pool.go
- pkg/runtime/runtime.go
- third_party/pools/resource_pool.go
> add resource pool MySQL conn check

- go.mod
- pkg/constants/mysql/constants.go
- pkg/mysql/client.go
- pkg/mysql/iterator.go
- pkg/mysql/statement.go
- pkg/runtime/runtime.go
- third_party/pools/resource_pool.go
- third_party/pools/resource_pool_flaky_test.go
mysql client add row iterator
Fixes #
```release-note
```
> add iterRow

- pkg/proto/runtime.go
- pkg/proto/schema_manager/loader.go
- pkg/proto/schema_manager/loader_test.go
- pkg/runtime/ast/insert.go
- pkg/runtime/optimize/optimizer.go
- pkg/runtime/optimize/optimizer_test.go
- testdata/mock_runtime.go
> support insert stmt rewrite and add mock schema loader

- go.mod
- pkg/executor/redirect.go
- pkg/runtime/ast/ast.go
- pkg/runtime/ast/drop_table.go
- pkg/runtime/ast/proto.go
- pkg/runtime/optimize/optimizer.go
- pkg/runtime/plan/drop_table.go
- pkg/runtime/plan/transparent.go
- test/integration_test.go
drop table
Fixes #129 
```release-note
```
> feat: drop table

- pkg/constants/mysql/constants.go
- pkg/executor/redirect.go
- pkg/mysql/server.go
- pkg/proto/interface.go
- pkg/security/tenant.go
Support non-db login.
**Which issue(s) this PR fixes**: #98 
Fixes #
```release-note
```
> feat: support non-db login

- pkg/mysql/execute_handle.go
- pkg/mysql/server.go
- pkg/runtime/optimize/optimizer.go
Routing of single-shard query will be correct.
Fixes #
```release-note
```
> fix: route single shard correctly

- pkg/proto/schema_manager/loader.go
> add table_schema filter to metadata loader sql

- pkg/mysql/rows.go
- pkg/runtime/optimize/optimizer.go
- pkg/runtime/plan/union.go
- pkg/runtime/runtime.go
- pkg/transformer/aggr_loader.go
- pkg/transformer/combiner.go
- test/integration_test.go
Fixes #123
```release-note
```
> Ftr: 针对shard之后的查询结果做聚合

- pkg/runtime/optimize/optimizer.go
- pkg/runtime/plan/aggregate.go
merge union to aggregate plan
Fixes #
```release-note
```
> imp: merge union to aggregate plan

- go.mod
- go.sum
- pkg/executor/redirect.go
- pkg/mysql/client.go
- pkg/mysql/client_test.go
- pkg/mysql/conn.go
- pkg/mysql/execute_handle.go
- pkg/mysql/iterator.go
- pkg/mysql/result.go
- pkg/mysql/server.go
- pkg/mysql/statement.go
- pkg/proto/data.go
- pkg/proto/interface.go
- pkg/proto/schema_manager/loader.go
- pkg/runtime/optimize/optimizer_test.go
- pkg/runtime/plan/drop_table.go
- pkg/runtime/plan/show_databases.go
- pkg/runtime/plan/show_tables.go
- pkg/runtime/plan/simple_delete.go
- pkg/runtime/plan/simple_insert.go
- pkg/runtime/plan/simple_select.go
- pkg/runtime/plan/truncate.go
- pkg/runtime/plan/union.go
- pkg/runtime/plan/update.go
- pkg/runtime/runtime.go
- pkg/transformer/combiner.go
- test/integration_test.go
> return data to client via channel

- pkg/runtime/ast/ast.go
- pkg/runtime/ast/join.go
- pkg/runtime/optimize/optimizer.go
- pkg/runtime/plan/simple_join.go
- test/integration_test.go
support A join B in one db
shard table join shard table
shard table join no shard table
Fixes #175
```release-note
```
> feat: simple join

- pkg/runtime/plan/simple_select.go
Fixes #155 
```release-note
```
> fix #155 return empty rows when query from information_schema.columns

- README.md
> Fix: fix readme dingtalk group image link.

- pkg/runtime/optimize/optimizer.go
- pkg/runtime/plan/show_index.go
Fixes #168 
```release-note
NONE
```
> feat:show index

- pkg/runtime/ast/ast.go
- pkg/runtime/ast/ast_test.go
- pkg/runtime/ast/describe.go
- pkg/runtime/ast/show.go
- pkg/runtime/optimize/optimizer.go
- pkg/runtime/plan/describle.go
> support "desc student id" grammar

- pkg/runtime/plan/union.go
> fix: execute union plan correctly

- pkg/runtime/optimize/optimizer.go
- test/integration_test.go
already support  on duplicate key update, but should not update shading key
Fixes #188 
```release-note
```
> feat: on duplicate key update

- README.md
- pkg/runtime/rule/shard_expr_parse.go
> chore: fix some small issue.

- pkg/runtime/ast/model.go
> improve: add unset methods for limit ast node

- pkg/mysql/client.go
- pkg/mysql/conn.go
- pkg/mysql/execute_handle.go
- pkg/mysql/server.go
arana com_field_list response issue
combine the fields into a package to send
Fixes #
```release-note
```
> fix: com_field_list  response, combine the fields into a package to send

- pkg/dataset/chain.go
- pkg/dataset/filter.go
- pkg/dataset/filter_test.go
- pkg/dataset/fuse.go
- pkg/dataset/fuse_test.go
- pkg/dataset/group_reduce.go
- pkg/dataset/group_reduce_test.go
- pkg/dataset/transform.go
- pkg/dataset/transform_test.go
- test/integration_test.go
Implement Group/Reduce for dataset api.
close #204 
close #203 
Fixes #
```release-note
```
> feat: implement group/reduce dataset

- pkg/executor/redirect.go
- pkg/mysql/rows/virtual_row.go
- pkg/runtime/optimize/optimizer.go
- pkg/runtime/plan/drop_index.go
- pkg/runtime/plan/transparent.go
- pkg/runtime/rule/shard_expr_parse.go
- scripts/init.sql
- scripts/sharding.sql
- test/integration_test.go
- test/suite.go
Fixes #
```release-note
drop index <name> on <logic table name>
- drop index <name> on <phy-schema.phy-table>
```
> fix: fix drop index need to send each shard

- pkg/dataset/dataset.go
- pkg/dataset/parallel.go
- pkg/dataset/parallel_test.go
**What this PR does**: implement  parallel and peekable dataset.
Fixes #202 
```release-note
```
> feat: peekable and parallel dataset

- pkg/runtime/ast/ast.go
- pkg/runtime/ast/show.go
- pkg/runtime/optimize/optimizer.go
- pkg/runtime/plan/show_columns.go
- test/integration_test.go
Support "show columns from tables" SQL statement.
Fixes #182
```release-note
```
> Support "show columns from tables" SQL statement.

- pkg/dataset/ordered.go
- pkg/dataset/ordered_test.go
- pkg/dataset/priority_queue.go
- pkg/dataset/priority_queue_test.go
add orderedDataset
Fixes #
#252 
```release-note
```
> feat(*): add orderedDataset

- pkg/mysql/execute_handle.go
Fixes #243
```release-note
```
> feat: add error log

- .github/workflows/github-actions.yml
- .github/workflows/reviewdog.yml
- Dockerfile
- go.mod
- go.sum
> feat: bump golang to 1.18

- .github/workflows/reviewdog.yml
- .pre-commit-config.yaml
- test/integration_test.go
- test/suite.go
> fix: remove some unnecessary ut to resolve CI failure

- pkg/sequence/snowflake/snowflake.go
> fix: fix sequence create table sql

- pkg/runtime/ast/ast.go
- pkg/runtime/ast/show.go
- pkg/runtime/optimize/optimizer.go
- pkg/runtime/plan/show_index.go
Fixes #273 
```release-note
NONE
```
> fix:show index

- pkg/dataset/chain.go
- pkg/dataset/group_reduce.go
- pkg/dataset/group_reduce_test.go
- pkg/merge/aggregator/init.go
- pkg/merge/aggregator/load_agg.go
- pkg/runtime/optimize/optimizer.go
- pkg/runtime/plan/group_plan.go
- pkg/transformer/aggr_loader.go
- pkg/transformer/combiner.go
support simple group by statement:
1. select elements should contain all group by items;
2. group by items should equal the order by items.
Fixes #169 
```release-note
```
> support group by plan

- pkg/executor/redirect.go
- pkg/mysql/conn.go
- pkg/mysql/thead/thead.go
- pkg/runtime/ast/ast.go
- pkg/runtime/ast/proto.go
- pkg/runtime/ast/show.go
- pkg/runtime/optimize/show_topology.go
- pkg/runtime/plan/show_databases.go
- pkg/runtime/plan/show_topology.go
Fixes #249 
```release-note
```
> Feature: Support "show topology from xxx" fix: #249

- pkg/config/api.go
- pkg/config/config.go
- pkg/config/etcd/etcd.go
- pkg/config/file/file.go
- pkg/config/nacos/nacos.go
- pkg/constants/env.go
- pkg/util/env/env.go
add develop environment
Fixes #248
```release-note
```
> feat: add develop environment

- pkg/dataset/group_reduce.go
- pkg/runtime/ast/ast.go
- pkg/runtime/ast/select_element.go
- pkg/runtime/optimize/dml/select.go
- pkg/runtime/plan/dml/group_plan.go
> support group by clause column complement

- pkg/schema/loader.go
Fixes #
#253 
```release-note
```
> refactor schemanager cache to lru cache

- pkg/config/file/file.go
- pkg/executor/redirect.go
- pkg/runtime/ast/ast.go
- pkg/runtime/ast/proto.go
- pkg/runtime/ast/show.go
- pkg/runtime/optimize/dal/show_status.go
- pkg/runtime/plan/dal/show_status.go
- pkg/runtime/runtime.go
- test/integration_test.go
> feat: support show status

- conf/config.yaml
- pkg/mysql/client.go
Fixes #292 
```release-note
```
> feat: max_allowed_packet is set by the user

- pkg/mysql/conn.go
- pkg/mysql/execute_handle.go
- pkg/mysql/server.go
Fixes #317 
```release-note
```
> debug: listen capabilities fix:#317

- pkg/runtime/ast/ast.go
- pkg/runtime/ast/proto.go
- pkg/runtime/ast/show.go
- pkg/runtime/optimize/dal/show_collation.go
- pkg/runtime/plan/dal/show_collation.go
- test/integration_test.go
Support "show collation" SQL statement. 
Fixes #272, #314
```release-note
```
> Support "show collation" SQL statement.

- pkg/proto/hint/hint.go
- pkg/runtime/optimize/dml/insert.go
- pkg/runtime/optimize/dml/select.go
- pkg/runtime/optimize/dml/update.go
- pkg/runtime/optimize/hints.go
- pkg/runtime/optimize/optimizer.go
- pkg/sequence/snowflake/snowflake.go
- test/integration_test.go
Fixes https://github.com/arana-db/arana/issues/296
```release-note
```
> hint fullscan

- pkg/mysql/execute_handle.go
Fixes #331 
```release-note
```
> fix:loop Reconnecting

- pkg/boot/discovery.go
- pkg/boot/proto.go
> feat(config): add config updater api

- scripts/init.sql
fix shadow_show not exist. 
Fixes #339
```release-note
```
> fix: shadow_show not exists

- pkg/admin/router/clusters.go
- pkg/boot/boot.go
- pkg/boot/discovery.go
- pkg/boot/proto.go
- pkg/dataset/reduce.go
> add http server api for cluster.

- integration_test/scene/db_tbl_rw/integration_test.go
- pkg/mysql/conn.go
**What this PR does**: render error message (table_not_found) correctly
Fixes #278
```release-note
```
> fix: render table_not_found error correctly

- pkg/admin/router/nodes.go
>  add  http api for nodes#344

- pkg/executor/redirect.go
- pkg/runtime/ast/ast.go
- pkg/runtime/ast/proto.go
- pkg/runtime/ast/show.go
- pkg/runtime/optimize/dal/show_warnings.go
- pkg/runtime/plan/dal/show_warnings.go
**What this PR does**: add show warnings
ref #360 
Fixes #
```release-note
```
> feat:add show warnings

- pkg/config/README.md
- pkg/constants/env_test.go
- pkg/constants/mysql/constants_test.go
- pkg/constants/mysql/type_test.go
> [chore] add config center doc & unit test.

- cmd/start/start.go
- conf/bootstrap.docker.yaml
- docker-compose.yaml
- example/local_server/main.go
- pkg/boot/discovery.go
- test/suite.go
1. use etcd in docker compose by default
2. auto-import configurations from yaml to etcd when starting over docker compose file
Fixes #
```release-note
```
> feat: use etcd in docker compose by default

- pkg/admin/router/nodes.go
> fix :bug:  HTTP API For UI

- pkg/config/api.go
- pkg/config/api_test.go
- pkg/config/default.go
- pkg/config/equals.go
- pkg/config/model_test.go
> fix:unit test

- pkg/runtime/rule/evaluator.go
- pkg/runtime/rule/shard_expr.go
- pkg/runtime/rule/shard_expr_parse.go
- pkg/runtime/rule/shard_expr_type.go
- pkg/runtime/rule/shard_expr_type_test.go
add Value.ToIntString() and using gxbig.Decimal to calculate the precise int value of float. such as the type of column id in table employee is int, while the 'id' value in user's sql is 3/2, its right value is 2.
> add Value.ToIntString()

- pkg/constants/env_test.go
- pkg/constants/mysql/constants_test.go
- pkg/executor/redirect.go
- pkg/runtime/ast/ast.go
- pkg/runtime/ast/proto.go
- pkg/runtime/ast/show.go
- pkg/runtime/optimize/dal/show_character_set.go
- pkg/runtime/plan/dal/show_character_set.go
- test/integration_test.go
Support SHOW CHARACTER SET Statement
Fixes #388 
```release-note
NONE
```
> [SQL] Support SHOW CHARACTER SET Statement

- pkg/dataset/chain.go
- pkg/dataset/filter.go
- pkg/runtime/plan/dal/constant.go
- pkg/runtime/plan/dal/show_table_status.go
- pkg/runtime/plan/dal/show_tables.go
Fixes #411 
```release-note
```
> feat:filter prefix table name

- .github/workflows/github-actions.yml
- go.mod
- go.sum
- pkg/runtime/ast/ast.go
> feat: upgrade parser to v0.2.5

- .dockerignore
- .github/workflows/go-integration.yml
- .github/workflows/go.yml
- conf/bootstrap.local-etcd.yaml
- pkg/admin/admin.go
- pkg/admin/router/misc.go
- pkg/admin/router/tenants.go
- pkg/boot/boot.go
- pkg/boot/discovery.go
- pkg/boot/discovery_watch.go
- pkg/boot/misc.go
- pkg/boot/misc_test.go
- pkg/boot/proto.go
- pkg/boot/watcher.go
- pkg/config/api.go
- pkg/config/config.go
- pkg/config/diff.go
- pkg/config/event.go
- pkg/proto/rule/rule.go
- pkg/runtime/namespace/command.go
- pkg/runtime/namespace/namespace.go
- pkg/runtime/runtime.go
- pkg/util/log/logging.go
watch configuration changes and update the runtime
Fixes #341 
```release-note
```
> feat: add runtime-level config watcher

- pkg/admin/router/clusters.go
- pkg/admin/router/db_groups.go
- pkg/admin/router/tenants.go
- pkg/boot/discovery.go
- pkg/boot/proto.go
What this PR does:
redefine object fields for arana-UI
Which issue(s) this PR fixes:
Special notes for your reviewer:
Does this PR introduce a user-facing change?:
> feat: redefine object fields for arana-UI

- .dockerignore
- .github/workflows/reviewdog.yml
- .pre-commit-config.yaml
- cmd/start/start.go
- go.mod
- pkg/admin/router/db_groups.go
- pkg/boot/discovery.go
- pkg/config/config.go
- pkg/config/equals.go
- pkg/config/etcd/etcd_test.go
- pkg/config/model.go
- pkg/constants/mysql/collations.go
- pkg/dataset/virtual_test.go
- pkg/merge/impl/group/group_stream_merge_rows.go
- pkg/mysql/auth.go
- pkg/mysql/auth_test.go
- pkg/mysql/client.go
- pkg/mysql/rows/virtual_row.go
- pkg/resultx/resultx.go
- pkg/runtime/optimize/dml/select.go
- pkg/runtime/rule/shard_expr_type.go
- pkg/runtime/rule/shard_script.go
- pkg/schema/loader.go
- pkg/trace/jaeger/jaeger.go
- pkg/util/bytefmt/bytefmt.go
- pkg/util/env/env.go
- staticcheck.conf
> ci: add staticcheck

- conf/config.yaml
- pkg/boot/boot.go
- pkg/constants/const.go
- pkg/executor/redirect.go
- pkg/runtime/namespace/command.go
- pkg/runtime/namespace/namespace.go
- pkg/runtime/runtime.go
Fixes #321 
```release-note
```
> feat: support slow log

- pkg/mysql/rows/virtual_row.go
- pkg/runtime/ast/ast.go
- pkg/runtime/ast/expression_atom.go
- pkg/runtime/plan/dml/mapping.go
- test/integration_test.go
handle `x DIV y` correctly
Fixes #
```release-note
```
> fix: incorrect behavior for intdiv operator

- conf/bootstrap.yaml
- pkg/boot/boot.go
- pkg/boot/discovery.go
- pkg/boot/proto.go
- pkg/config/model.go
- pkg/mysql/server.go
- pkg/runtime/namespace/command.go
- pkg/runtime/namespace/namespace.go
- pkg/runtime/runtime.go
- pkg/util/log/logging.go
> feat:solo slow logger

- README.md
- README_CN.md
- README_ZH.md
> docs:updated features

- conf/bootstrap.yaml
> style: use root path

- README.md
> Format readme.

- .github/workflows/changelog.yml
add changelog action
#390 
Fixes #390 
```release-note
```
> Feat:add changelog github workflow action

- integration_test/scene/db/integration_test.go
- integration_test/scene/db_tbl/integration_test.go
- integration_test/scene/db_tbl_rw/integration_test.go
- integration_test/scene/tbl/integration_test.go
- test/dataset.go
Fixes #466
```release-note
```
> fix：针对集成测试的参数进行逻辑校验

- .dockerignore
- Dockerfile
- pkg/admin/admin.api.yaml
- pkg/admin/admin.go
- pkg/config/mock/mock_config.go
> feat: docker integration with arana ui

- Dockerfile
- conf/bootstrap.yaml
- pkg/boot/discovery.go
- pkg/config/model.go
- pkg/util/log/logging.go
refine logger
Fixes https://github.com/arana-db/arana/issues/419
```release-note
```
> refine logger

- pkg/admin/router/nodes.go
- pkg/boot/discovery.go
- pkg/boot/proto.go
- pkg/config/api.go
- pkg/config/tenant.go
> add node config support (#464)

- pkg/boot/discovery.go
add table config discovery support
Fixes #
```release-note
```
> feat(config): add sharding_rule table config support

- pkg/admin/admin.api.yaml
- pkg/admin/router/clusters.go
- pkg/admin/router/db_groups.go
- pkg/boot/discovery.go
fix clusters/group crud
Fixes #
```release-note
```
> fix(admin): fix cluster/group crud api

- pkg/runtime/function2/cast_charset.go
- pkg/runtime/function2/char_charset_test.go
- pkg/util/charsetconv/charsetconv.go
- pkg/util/charsetconv/charsetconv_test.go
Support MySQL Cast Charset function
Fixes #https://github.com/arana-db/arana/issues/477
```release-note
```
> feat: Support MySQL Cast Charset function

- pkg/runtime/function2/cast.go
- pkg/runtime/function2/cast_test.go
cast unsign
Fixes #460 
```release-note
```
> feat: cast unsign func

- pkg/runtime/function2/concat_ws.go
- pkg/runtime/function2/concat_ws_test.go
Signed-off-by: charlie <charlie1213800@gmail.com>
support the func [concast_ws](https://dev.mysql.com/doc/refman/5.6/en/string-functions.html#function_concat-ws)
Fixes #505 
```release-note
NONE
```
> feat: support the func concast_ws

- pkg/admin/admin.api.yaml
- pkg/admin/router/clusters.go
- pkg/admin/router/db_groups.go
- pkg/admin/router/tables.go
- pkg/boot/discovery.go
add table open api
Fixes #
```release-note
```
> feat(admin): add table open api

- pkg/runtime/function/lower.go
- pkg/runtime/function/lower_test.go
Fixes #517 
```release-note
```
> feat: Support MySQL Lower function

- go.mod
- go.sum
- pkg/executor/redirect.go
- pkg/runtime/ast/proto.go
- pkg/runtime/ast/show.go
- pkg/runtime/optimize/dal/show_replica_status.go
- pkg/runtime/plan/dal/show_replica_status.go
- test/integration_test.go
Fixes #494 
```release-note
```
> feat(sql): support show replica status SQL statement. (arana#494)

- cmd/admin/admin.go
- pkg/admin/admin.go
- pkg/admin/config.go
- pkg/admin/config_service.go
- pkg/admin/router/clusters.go
- pkg/admin/router/db_groups.go
- pkg/admin/router/nodes.go
- pkg/admin/router/tables.go
- pkg/admin/router/tenants.go
- pkg/admin/router/users.go
- pkg/boot/discovery.go
- pkg/boot/proto.go
- pkg/config/model.go
- pkg/util/misc/misc.go
- test/integration_test.go
> refactor: add standalone config service for admin module

- go.mod
- go.sum
- pkg/executor/redirect.go
- pkg/runtime/ast/ast.go
- pkg/runtime/ast/optimize_table.go
- pkg/runtime/ast/proto.go
- pkg/runtime/optimize/ddl/optimize_table.go
- pkg/runtime/plan/ddl/optimize_table.go
- test/integration_test.go
**What this PR does**: https://github.com/arana-db/arana/issues/384
Fixes #
```release-note
```
> add support for optimize table statement

- pkg/runtime/function/strcmp.go
- pkg/runtime/function/strcmp_test.go
Fixes #539 
```release-note
```
> [SQL] Support MySQL STRCMP function. 

- pkg/runtime/function/left.go
- pkg/runtime/function/left_test.go
Support MySql LEFT function
Fixes # https://github.com/arana-db/arana/issues/518
```release-note
```
> Support MySQL LEFT function

- pkg/executor/redirect.go
- pkg/runtime/ast/ast.go
- pkg/runtime/ast/kill.go
- pkg/runtime/ast/proto.go
- pkg/runtime/optimize/dal/kill.go
- pkg/runtime/plan/dal/kill.go
- pkg/runtime/plan/dal/show_process_list.go
- pkg/util/math/sal.go
- pkg/util/math/sal_test.go
- test/integration_test.go
Signed-off-by: Charlie17Li <charlie1213800@gmail.com>
support kill statement
Fixes #533 
```release-note
```
> feat: support kill statement

- pkg/runtime/function/space.go
- pkg/runtime/function/space_test.go
> refactor space function.

- pkg/executor/redirect.go
- pkg/mysql/execute_handle.go
- pkg/mysql/server.go
- pkg/proto/interface.go
- pkg/runtime/function/space_test.go
Fixes #247 
```release-note
```
> feat: implement basic multiple query

- pkg/boot/watcher.go
- pkg/config/config_watcher.go
Fixes #490 
```release-note
```
> Fix: watch event bug in config center 

- go.mod
- go.sum
- pkg/executor/redirect.go
- pkg/runtime/ast/ast.go
- pkg/runtime/ast/check_table.go
- pkg/runtime/ast/proto.go
- pkg/runtime/optimize/ddl/check_table.go
- pkg/runtime/plan/ddl/check_table.go
- test/integration_test.go
[SQL] Support CHECK TABLE Statement #386
> [SQL] Support CHECK TABLE Statement #386

- .github/workflows/changelog.yml
fix 
`
Invalid workflow file: releases is not a valid event name
`
Fixes #
```release-note
```
> fix(ci): fix workflow event spell error

- pkg/registry/etcd/registery.go
Fixes #651 
```release-note
```
> fix: Registry etcd of too large lease TTL

- conf/config.yaml
- pkg/boot/discovery.go
- pkg/boot/misc.go
- pkg/config/equals.go
- pkg/config/model.go
- pkg/proto/rule/rule.go
- pkg/runtime/optimize/dml/insert.go
- pkg/runtime/rule/shard_script.go
Fixes https://github.com/arana-db/arana/issues/425
```release-note
```
> composite_sharding

- pkg/proto/value.go
- pkg/runtime/ast/ast.go
- pkg/runtime/ast/create_table.go
- pkg/runtime/ast/expression_atom.go
- pkg/runtime/ast/proto.go
- pkg/runtime/ast/show.go
- pkg/runtime/plan/dal/show_databases.go
- pkg/runtime/plan/dal/show_tables.go
support show databases SQL statement with where clause.
Fixes #672 
```release-note
```
> Support show databases SQL statement with where clause(#672)

- conf/bootstrap.local-etcd.yaml
- conf/bootstrap.yaml
- pkg/boot/boot.go
- pkg/config/misc.go
- pkg/config/model.go
- pkg/runtime/namespace/command.go
- pkg/util/log/logging.go
- testdata/fake_bootstrap.yaml
add :logging_config in yaml, LoggingConfig
delete : const (env) GetEnvValue
fix : model bootOptions
fixes: #650
> clean arana project log output 

- go.mod
- go.sum
- pkg/boot/boot.go
- pkg/boot/watcher.go
- pkg/executor/redirect.go
- pkg/mysql/thead/thead.go
- pkg/proto/rule/rule.go
- pkg/runtime/ast/ast.go
- pkg/runtime/ast/proto.go
- pkg/runtime/ast/show.go
- pkg/runtime/optimize/dal/show_database_rule.go
- pkg/runtime/plan/dal/show_database_rules.go
- pkg/runtime/plan/dal/show_database_rules_test.go
- test/integration_test.go
support `show database rule from`
Fixes #627
```release-note
```
> feature: support show database rule from

- conf/config.yaml
- integration_test/config/db/config.yaml
- integration_test/config/db_tbl/config.yaml
- integration_test/config/db_tbl_rw/config.yaml
- integration_test/config/tbl/config.yaml
- pkg/config/api.go
- pkg/config/config_reader.go
- pkg/config/config_test.go
- pkg/config/model.go
- pkg/config/path.go
- pkg/runtime/tenant/tenant.go
- pkg/runtime/transaction/trx_log.go
- pkg/runtime/transaction/trx_manager.go
- testdata/fake_config.yaml
Tx clean log
Fixes #556 
```release-note
```
> feat: Auto clean transaction log

- Makefile
> fix go test

- .github/workflows/codeql-analysis.yml
- Makefile
> fix CodeQL problems

- .github/workflows/codeql-analysis.yml
- Makefile
> Revert 702 master

- pkg/runtime/function/concat_ws_test.go
- pkg/runtime/function/cume_dist_test.go
- pkg/runtime/function/dense_rank_test.go
> feat(test): add unit test for function

- pkg/security/tenant_test.go
Fixes #730 
```release-note
NONE
```
> test: security ut

- pkg/security/tenant_test.go
Fixes #750 
```release-note
NONE
```
> fix: security ut tenants sort

- pkg/util/bufferpool/bufferpool_test.go
- pkg/util/bytefmt/bytefmt_test.go
- pkg/util/config/config_test.go
> feat(test): add unit test

- go.mod
- pkg/util/misc/misc_test.go
This PR is UT for /pkg/util/misc 
Fixes #
```release-note
```
> unit test cases for /pkg/util/misc

- pkg/merge/aggregator/loag_agg_test.go
add unit test for pkg/merge.
Fixes #709 
```release-note
```
> test: add unit test for pkg/merge

- pkg/config/equals_test.go
- pkg/config/misc_test.go
For #777 #775 
```release-note
```
> test: add unit test

- conf/bootstrap.yaml
> feat: update boostrap.yaml log config
